### ISSUE TITLE
Need release with all changes

### ISSUE THREAD

**Issue by max-dreamsoft** [alhimik1986/yii2_crud_module#2]
Фиксы по settings не попали в релиз. Можно зарелизить, например, 1.1?

**Comment by alhimik1986** [comment]
Пофиксил. Релиз 1.01. Но советую всю папку alhimik1986 удалить и заново заинстраллировать и очистить папку assets.

При использовании jQuery 3 перестаёт работать перемещение формы в тачскринах (мобильных устройствах). А перемещение мышкой работает при любом jQuery.

**Comment by max-dreamsoft** [comment]
Спасибо
